server:
  port: 5002

spring:
  sleuth:
    enabled: false
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

zipkin:
  storage:
    type: elasticsearch
    elasticsearch:
      hosts: 106.14.69.75:9201
      cluster: elasticsearch
      index: zipkin
      max-requests: 64
      index-shards: 5
      index-replicas: 1