server:
  port: 4060

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
#    password: ENC(gc16brBHPNq27HsjaULgKGq00Rz6ZUji)
    password: admin
    url: jdbc:mysql://127.00.1:3306/pig?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  elasticjob:
    zookeeper:
      server-lists: 106.14.69.75:2181
      namespace: pig-daemon